### ISSUE TITLE
Nov 13 sprint

### ISSUE THREAD

**Issue by sachinr** [Zipper-Inc/zipper-functions#603]
- [x] @sachinr - Send emails from Slack #602 
- [x] @sachinr - spec Connectors v2 
- [x] @sachinr - Get Facet.ai onboarded
- [x] @sachinr - Clerk adwords
- [ ] @imadha - twind & react stacks #549 #551 
- [ ] @imadha - framework v2 prototype (Hono swap-in)
- [x] @imadha / @miguel-nascimento  - run page perf (50% faster) #605 
- [x] @arielconti10 / @antoniel  - DB connectors #555 #553 #554 - #616
- [x] @arielconti10 - Raycast blog post 
- [ ] @arielconti10  - Fix uploadthing bugs
- [ ] @arielconti10  - profile page updates
- [x] @MatheusLittig - Notion connector #266 
- [x] @MatheusLittig - Discord connector #566 
- [x] @MatheusLittig - MDX #550 
- [x] @MatheusLittig - June blog post #569 
- [x] @MatheusLittig - Gallery in the Dashboard
- [x] @MatheusLittig - Better meta tags
- [ ] @antoniel - Postbin blog posts
- [x] @antoniel - Fix request object in Context 
#612 feat(relay): adds body and queryParams to context.originalRequest
- [ ] @miguel-nascimento - ts/tsx support 
- [ ] @miguel-nascimento - finish up LLM utils #557
